// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	"sync"
)

// Ensure, that StorageMock does implement Storage.
// If this is not the case, regenerate this file with moq.
var _ Storage = &StorageMock{}

// StorageMock is a mock implementation of Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked Storage
//		mockedStorage := &StorageMock{
//			DeleteItemFunc: func(ctx context.Context, userID string, itemName string) error {
//				panic("mock out the DeleteItem method")
//			},
//			DeleteUserFunc: func(ctx context.Context, userID string) error {
//				panic("mock out the DeleteUser method")
//			},
//			ReadItemFunc: func(ctx context.Context, userID string, itemName string) ([]byte, error) {
//				panic("mock out the ReadItem method")
//			},
//			WriteItemFunc: func(ctx context.Context, userID string, itemName string, content []byte) error {
//				panic("mock out the WriteItem method")
//			},
//		}
//
//		// use mockedStorage in code that requires Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// DeleteItemFunc mocks the DeleteItem method.
	DeleteItemFunc func(ctx context.Context, userID string, itemName string) error

	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, userID string) error

	// ReadItemFunc mocks the ReadItem method.
	ReadItemFunc func(ctx context.Context, userID string, itemName string) ([]byte, error)

	// WriteItemFunc mocks the WriteItem method.
	WriteItemFunc func(ctx context.Context, userID string, itemName string, content []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteItem holds details about calls to the DeleteItem method.
		DeleteItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// ItemName is the itemName argument value.
			ItemName string
		}
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// ReadItem holds details about calls to the ReadItem method.
		ReadItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// ItemName is the itemName argument value.
			ItemName string
		}
		// WriteItem holds details about calls to the WriteItem method.
		WriteItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// ItemName is the itemName argument value.
			ItemName string
			// Content is the content argument value.
			Content []byte
		}
	}
	lockDeleteItem sync.RWMutex
	lockDeleteUser sync.RWMutex
	lockReadItem   sync.RWMutex
	lockWriteItem  sync.RWMutex
}

// DeleteItem calls DeleteItemFunc.
func (mock *StorageMock) DeleteItem(ctx context.Context, userID string, itemName string) error {
	if mock.DeleteItemFunc == nil {
		panic("StorageMock.DeleteItemFunc: method is nil but Storage.DeleteItem was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   string
		ItemName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		ItemName: itemName,
	}
	mock.lockDeleteItem.Lock()
	mock.calls.DeleteItem = append(mock.calls.DeleteItem, callInfo)
	mock.lockDeleteItem.Unlock()
	return mock.DeleteItemFunc(ctx, userID, itemName)
}

// DeleteItemCalls gets all the calls that were made to DeleteItem.
// Check the length with:
//
//	len(mockedStorage.DeleteItemCalls())
func (mock *StorageMock) DeleteItemCalls() []struct {
	Ctx      context.Context
	UserID   string
	ItemName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   string
		ItemName string
	}
	mock.lockDeleteItem.RLock()
	calls = mock.calls.DeleteItem
	mock.lockDeleteItem.RUnlock()
	return calls
}

// DeleteUser calls DeleteUserFunc.
func (mock *StorageMock) DeleteUser(ctx context.Context, userID string) error {
	if mock.DeleteUserFunc == nil {
		panic("StorageMock.DeleteUserFunc: method is nil but Storage.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, userID)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedStorage.DeleteUserCalls())
func (mock *StorageMock) DeleteUserCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// ReadItem calls ReadItemFunc.
func (mock *StorageMock) ReadItem(ctx context.Context, userID string, itemName string) ([]byte, error) {
	if mock.ReadItemFunc == nil {
		panic("StorageMock.ReadItemFunc: method is nil but Storage.ReadItem was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   string
		ItemName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		ItemName: itemName,
	}
	mock.lockReadItem.Lock()
	mock.calls.ReadItem = append(mock.calls.ReadItem, callInfo)
	mock.lockReadItem.Unlock()
	return mock.ReadItemFunc(ctx, userID, itemName)
}

// ReadItemCalls gets all the calls that were made to ReadItem.
// Check the length with:
//
//	len(mockedStorage.ReadItemCalls())
func (mock *StorageMock) ReadItemCalls() []struct {
	Ctx      context.Context
	UserID   string
	ItemName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   string
		ItemName string
	}
	mock.lockReadItem.RLock()
	calls = mock.calls.ReadItem
	mock.lockReadItem.RUnlock()
	return calls
}

// WriteItem calls WriteItemFunc.
func (mock *StorageMock) WriteItem(ctx context.Context, userID string, itemName string, content []byte) error {
	if mock.WriteItemFunc == nil {
		panic("StorageMock.WriteItemFunc: method is nil but Storage.WriteItem was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   string
		ItemName string
		Content  []byte
	}{
		Ctx:      ctx,
		UserID:   userID,
		ItemName: itemName,
		Content:  content,
	}
	mock.lockWriteItem.Lock()
	mock.calls.WriteItem = append(mock.calls.WriteItem, callInfo)
	mock.lockWriteItem.Unlock()
	return mock.WriteItemFunc(ctx, userID, itemName, content)
}

// WriteItemCalls gets all the calls that were made to WriteItem.
// Check the length with:
//
//	len(mockedStorage.WriteItemCalls())
func (mock *StorageMock) WriteItemCalls() []struct {
	Ctx      context.Context
	UserID   string
	ItemName string
	Content  []byte
} {
	var calls []struct {
		Ctx      context.Context
		UserID   string
		ItemName string
		Content  []byte
	}
	mock.lockWriteItem.RLock()
	calls = mock.calls.WriteItem
	mock.lockWriteItem.RUnlock()
	return calls
}
