// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type DeltaEvent struct {
	ID              int64  `json:"id"`
	EventUuid       string `json:"event_uuid"`
	JoplinID        string `json:"joplin_id"`
	UserID          string `json:"user_id"`
	FileName        string `json:"file_name"`
	PreviousShareID string `json:"previous_share_id"`
	ItemType        int64  `json:"item_type"`
	EventType       int64  `json:"event_type"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	AuthCode  string `json:"auth_code"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Share struct {
	ID        string `json:"id"`
	OwnerID   string `json:"owner_id"`
	FolderID  string `json:"folder_id"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncItem struct {
	ID              string `json:"id"`
	FileName        string `json:"file_name"`
	MimeType        string `json:"mime_type"`
	JoplinID        string `json:"joplin_id"`
	ParentID        string `json:"parent_id"`
	ShareID         string `json:"share_id"`
	ItemType        int64  `json:"item_type"`
	IsEncrypted     int64  `json:"is_encrypted"`
	ClientUpdatedAt int64  `json:"client_updated_at"`
	OwnerID         string `json:"owner_id"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type SyncLock struct {
	ID       int64  `json:"id"`
	LockKey  string `json:"lock_key"`
	LockType int64  `json:"lock_type"`
	LockData string `json:"lock_data"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type UserShare struct {
	ID        int64  `json:"id"`
	ShareID   string `json:"share_id"`
	UserID    string `json:"user_id"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserSyncItem struct {
	ID         int64  `json:"id"`
	UserID     string `json:"user_id"`
	SyncItemID string `json:"sync_item_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}
