// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Changes2 struct {
	Counter         int64  `json:"counter"`
	ID              string `json:"id"`
	ItemID          string `json:"item_id"`
	UserID          string `json:"user_id"`
	ItemName        string `json:"item_name"`
	PreviousShareID string `json:"previous_share_id"`
	ItemType        int64  `json:"item_type"`
	Type            int64  `json:"type"`
	CreatedTime     int64  `json:"created_time"`
	UpdatedTime     int64  `json:"updated_time"`
}

type Item struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	MimeType             string `json:"mime_type"`
	Content              []byte `json:"content"`
	ContentSize          int64  `json:"content_size"`
	JopID                string `json:"jop_id"`
	JopParentID          string `json:"jop_parent_id"`
	JopShareID           string `json:"jop_share_id"`
	JopType              int64  `json:"jop_type"`
	JopEncryptionApplied int64  `json:"jop_encryption_applied"`
	JopUpdatedTime       int64  `json:"jop_updated_time"`
	OwnerID              string `json:"owner_id"`
	ContentStorageID     int64  `json:"content_storage_id"`
	CreatedTime          int64  `json:"created_time"`
	UpdatedTime          int64  `json:"updated_time"`
}

type KeyValue struct {
	ID    int64  `json:"id"`
	Key   string `json:"key"`
	Type  int64  `json:"type"`
	Value string `json:"value"`
}

type Session struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	AuthCode    string `json:"auth_code"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type Storage struct {
	ID               int64  `json:"id"`
	ConnectionString string `json:"connection_string"`
	CreatedTime      int64  `json:"created_time"`
	UpdatedTime      int64  `json:"updated_time"`
}

type User struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	FullName    string `json:"full_name"`
	IsAdmin     int64  `json:"is_admin"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type UserItem struct {
	ID          int64  `json:"id"`
	UserID      string `json:"user_id"`
	ItemID      string `json:"item_id"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}
