// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserShare(ctx context.Context, arg CreateUserShareParams) (UserShare, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUserId(ctx context.Context, userID string) error
	DeleteSyncItemByFileNameAndUser(ctx context.Context, arg DeleteSyncItemByFileNameAndUserParams) error
	DeleteSyncLock(ctx context.Context, lockKey string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserSyncItem(ctx context.Context, arg DeleteUserSyncItemParams) error
	GetDeltaEventsByUser(ctx context.Context, arg GetDeltaEventsByUserParams) ([]DeltaEvent, error)
	GetInstanceStats(ctx context.Context) (GetInstanceStatsRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSyncItemByFileNameAndUser(ctx context.Context, arg GetSyncItemByFileNameAndUserParams) (SyncItem, error)
	GetSyncLock(ctx context.Context, lockKey string) (SyncLock, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserStats(ctx context.Context) ([]GetUserStatsRow, error)
	InsertDeltaEvent(ctx context.Context, arg InsertDeltaEventParams) (DeltaEvent, error)
	InsertShareTombstonesForDeletedUser(ctx context.Context, arg InsertShareTombstonesForDeletedUserParams) error
	ListSyncItemsByUser(ctx context.Context, arg ListSyncItemsByUserParams) ([]SyncItem, error)
	ListSyncLocksByType(ctx context.Context, lockType int64) ([]SyncLock, error)
	SetSyncLock(ctx context.Context, arg SetSyncLockParams) (SyncLock, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertSyncItem(ctx context.Context, arg UpsertSyncItemParams) (SyncItem, error)
	UpsertUserSyncItem(ctx context.Context, arg UpsertUserSyncItemParams) (UserSyncItem, error)
}

var _ Querier = (*Queries)(nil)
