// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id, user_id, auth_code, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, user_id, auth_code, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	AuthCode  string `json:"auth_code"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AuthCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShare = `-- name: CreateShare :one
INSERT INTO shares (
  id, owner_id, folder_id, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, owner_id, folder_id, created_at, updated_at
`

type CreateShareParams struct {
	ID        string `json:"id"`
	OwnerID   string `json:"owner_id"`
	FolderID  string `json:"folder_id"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, createShare,
		arg.ID,
		arg.OwnerID,
		arg.FolderID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, password_hash, is_admin, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, email, password_hash, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserShare = `-- name: CreateUserShare :one
INSERT INTO user_shares (
  share_id, user_id, status, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, share_id, user_id, status, created_at, updated_at
`

type CreateUserShareParams struct {
	ShareID   string `json:"share_id"`
	UserID    string `json:"user_id"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateUserShare(ctx context.Context, arg CreateUserShareParams) (UserShare, error) {
	row := q.db.QueryRowContext(ctx, createUserShare,
		arg.ShareID,
		arg.UserID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserShare
	err := row.Scan(
		&i.ID,
		&i.ShareID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSyncItemByFileNameAndUser = `-- name: DeleteSyncItemByFileNameAndUser :exec
DELETE FROM sync_items
WHERE file_name = ? AND id IN (
  SELECT sync_item_id FROM user_sync_items WHERE user_id = ?
)
`

type DeleteSyncItemByFileNameAndUserParams struct {
	FileName string `json:"file_name"`
	UserID   string `json:"user_id"`
}

func (q *Queries) DeleteSyncItemByFileNameAndUser(ctx context.Context, arg DeleteSyncItemByFileNameAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteSyncItemByFileNameAndUser, arg.FileName, arg.UserID)
	return err
}

const deleteSyncLock = `-- name: DeleteSyncLock :exec
DELETE FROM sync_locks
WHERE lock_key = ?
`

func (q *Queries) DeleteSyncLock(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, deleteSyncLock, lockKey)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserSyncItem = `-- name: DeleteUserSyncItem :exec
DELETE FROM user_sync_items
WHERE user_id = ? AND sync_item_id = ?
`

type DeleteUserSyncItemParams struct {
	UserID     string `json:"user_id"`
	SyncItemID string `json:"sync_item_id"`
}

func (q *Queries) DeleteUserSyncItem(ctx context.Context, arg DeleteUserSyncItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSyncItem, arg.UserID, arg.SyncItemID)
	return err
}

const getDeltaEventsByUser = `-- name: GetDeltaEventsByUser :many
SELECT id, event_uuid, joplin_id, user_id, file_name, previous_share_id, item_type, event_type, created_at, updated_at FROM delta_events
WHERE user_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type GetDeltaEventsByUserParams struct {
	UserID string `json:"user_id"`
	ID     int64  `json:"id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetDeltaEventsByUser(ctx context.Context, arg GetDeltaEventsByUserParams) ([]DeltaEvent, error) {
	rows, err := q.db.QueryContext(ctx, getDeltaEventsByUser, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeltaEvent
	for rows.Next() {
		var i DeltaEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventUuid,
			&i.JoplinID,
			&i.UserID,
			&i.FileName,
			&i.PreviousShareID,
			&i.ItemType,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstanceStats = `-- name: GetInstanceStats :one
SELECT 
  (SELECT COUNT(*) FROM users) as total_users,
  (SELECT COUNT(*) FROM sync_items) as total_items
`

type GetInstanceStatsRow struct {
	TotalUsers int64 `json:"total_users"`
	TotalItems int64 `json:"total_items"`
}

func (q *Queries) GetInstanceStats(ctx context.Context) (GetInstanceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceStats)
	var i GetInstanceStatsRow
	err := row.Scan(&i.TotalUsers, &i.TotalItems)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, auth_code, created_at, updated_at FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncItemByFileNameAndUser = `-- name: GetSyncItemByFileNameAndUser :one
SELECT sync_items.id, sync_items.file_name, sync_items.mime_type, sync_items.joplin_id, sync_items.parent_id, sync_items.share_id, sync_items.item_type, sync_items.is_encrypted, sync_items.client_updated_at, sync_items.owner_id, sync_items.created_at, sync_items.updated_at FROM sync_items
JOIN user_sync_items ON sync_items.id = user_sync_items.sync_item_id
WHERE sync_items.file_name = ? AND user_sync_items.user_id = ?
LIMIT 1
`

type GetSyncItemByFileNameAndUserParams struct {
	FileName string `json:"file_name"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetSyncItemByFileNameAndUser(ctx context.Context, arg GetSyncItemByFileNameAndUserParams) (SyncItem, error) {
	row := q.db.QueryRowContext(ctx, getSyncItemByFileNameAndUser, arg.FileName, arg.UserID)
	var i SyncItem
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.JoplinID,
		&i.ParentID,
		&i.ShareID,
		&i.ItemType,
		&i.IsEncrypted,
		&i.ClientUpdatedAt,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncLock = `-- name: GetSyncLock :one
SELECT id, lock_key, lock_type, lock_data FROM sync_locks
WHERE lock_key = ? LIMIT 1
`

func (q *Queries) GetSyncLock(ctx context.Context, lockKey string) (SyncLock, error) {
	row := q.db.QueryRowContext(ctx, getSyncLock, lockKey)
	var i SyncLock
	err := row.Scan(
		&i.ID,
		&i.LockKey,
		&i.LockType,
		&i.LockData,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, is_admin, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_admin, created_at, updated_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :many
SELECT 
  users.id as user_id, 
  users.email,
  users.is_admin,
  users.created_at,
  COUNT(user_sync_items.sync_item_id) as total_items
FROM users
LEFT JOIN user_sync_items ON users.id = user_sync_items.user_id
GROUP BY users.id, users.email, users.is_admin, users.created_at
ORDER BY users.created_at ASC
`

type GetUserStatsRow struct {
	UserID     string `json:"user_id"`
	Email      string `json:"email"`
	IsAdmin    int64  `json:"is_admin"`
	CreatedAt  int64  `json:"created_at"`
	TotalItems int64  `json:"total_items"`
}

func (q *Queries) GetUserStats(ctx context.Context) ([]GetUserStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserStatsRow
	for rows.Next() {
		var i GetUserStatsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeltaEvent = `-- name: InsertDeltaEvent :one
INSERT INTO delta_events (
  event_uuid, joplin_id, user_id, file_name, previous_share_id, item_type, event_type, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, event_uuid, joplin_id, user_id, file_name, previous_share_id, item_type, event_type, created_at, updated_at
`

type InsertDeltaEventParams struct {
	EventUuid       string `json:"event_uuid"`
	JoplinID        string `json:"joplin_id"`
	UserID          string `json:"user_id"`
	FileName        string `json:"file_name"`
	PreviousShareID string `json:"previous_share_id"`
	ItemType        int64  `json:"item_type"`
	EventType       int64  `json:"event_type"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) InsertDeltaEvent(ctx context.Context, arg InsertDeltaEventParams) (DeltaEvent, error) {
	row := q.db.QueryRowContext(ctx, insertDeltaEvent,
		arg.EventUuid,
		arg.JoplinID,
		arg.UserID,
		arg.FileName,
		arg.PreviousShareID,
		arg.ItemType,
		arg.EventType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DeltaEvent
	err := row.Scan(
		&i.ID,
		&i.EventUuid,
		&i.JoplinID,
		&i.UserID,
		&i.FileName,
		&i.PreviousShareID,
		&i.ItemType,
		&i.EventType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShareTombstonesForDeletedUser = `-- name: InsertShareTombstonesForDeletedUser :exec
INSERT INTO delta_events (
  event_uuid, joplin_id, user_id, file_name, previous_share_id, item_type, event_type, created_at, updated_at
)
SELECT 
  lower(hex(randomblob(16))),
  sync_items.id,
  user_shares.user_id,
  sync_items.file_name,
  sync_items.share_id,
  sync_items.item_type,
  3,
  ?,
  ?
FROM sync_items
JOIN shares ON sync_items.share_id = shares.id
JOIN user_shares ON shares.id = user_shares.share_id
WHERE shares.owner_id = ?
`

type InsertShareTombstonesForDeletedUserParams struct {
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) InsertShareTombstonesForDeletedUser(ctx context.Context, arg InsertShareTombstonesForDeletedUserParams) error {
	_, err := q.db.ExecContext(ctx, insertShareTombstonesForDeletedUser, arg.CreatedAt, arg.UpdatedAt, arg.OwnerID)
	return err
}

const listSyncItemsByUser = `-- name: ListSyncItemsByUser :many
SELECT sync_items.id, sync_items.file_name, sync_items.mime_type, sync_items.joplin_id, sync_items.parent_id, sync_items.share_id, sync_items.item_type, sync_items.is_encrypted, sync_items.client_updated_at, sync_items.owner_id, sync_items.created_at, sync_items.updated_at FROM sync_items
JOIN user_sync_items ON sync_items.id = user_sync_items.sync_item_id
WHERE user_sync_items.user_id = ?
ORDER BY sync_items.updated_at ASC
LIMIT ? OFFSET ?
`

type ListSyncItemsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListSyncItemsByUser(ctx context.Context, arg ListSyncItemsByUserParams) ([]SyncItem, error) {
	rows, err := q.db.QueryContext(ctx, listSyncItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncItem
	for rows.Next() {
		var i SyncItem
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.MimeType,
			&i.JoplinID,
			&i.ParentID,
			&i.ShareID,
			&i.ItemType,
			&i.IsEncrypted,
			&i.ClientUpdatedAt,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncLocksByType = `-- name: ListSyncLocksByType :many
SELECT id, lock_key, lock_type, lock_data FROM sync_locks
WHERE lock_type = ?
`

func (q *Queries) ListSyncLocksByType(ctx context.Context, lockType int64) ([]SyncLock, error) {
	rows, err := q.db.QueryContext(ctx, listSyncLocksByType, lockType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncLock
	for rows.Next() {
		var i SyncLock
		if err := rows.Scan(
			&i.ID,
			&i.LockKey,
			&i.LockType,
			&i.LockData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, is_admin, created_at, updated_at FROM users
ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSyncLock = `-- name: SetSyncLock :one
INSERT INTO sync_locks (
  lock_key, lock_type, lock_data
) VALUES (
  ?, ?, ?
)
ON CONFLICT(lock_key) DO UPDATE SET
  lock_type = excluded.lock_type,
  lock_data = excluded.lock_data
RETURNING id, lock_key, lock_type, lock_data
`

type SetSyncLockParams struct {
	LockKey  string `json:"lock_key"`
	LockType int64  `json:"lock_type"`
	LockData string `json:"lock_data"`
}

func (q *Queries) SetSyncLock(ctx context.Context, arg SetSyncLockParams) (SyncLock, error) {
	row := q.db.QueryRowContext(ctx, setSyncLock, arg.LockKey, arg.LockType, arg.LockData)
	var i SyncLock
	err := row.Scan(
		&i.ID,
		&i.LockKey,
		&i.LockType,
		&i.LockData,
	)
	return i, err
}

const upsertSyncItem = `-- name: UpsertSyncItem :one
INSERT INTO sync_items (
  id, file_name, mime_type, joplin_id, parent_id, share_id,
  item_type, is_encrypted, client_updated_at, owner_id,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  file_name = excluded.file_name,
  mime_type = excluded.mime_type,
  joplin_id = excluded.joplin_id,
  parent_id = excluded.parent_id,
  share_id = excluded.share_id,
  item_type = excluded.item_type,
  is_encrypted = excluded.is_encrypted,
  client_updated_at = excluded.client_updated_at,
  owner_id = excluded.owner_id,
  updated_at = excluded.updated_at
RETURNING id, file_name, mime_type, joplin_id, parent_id, share_id, item_type, is_encrypted, client_updated_at, owner_id, created_at, updated_at
`

type UpsertSyncItemParams struct {
	ID              string `json:"id"`
	FileName        string `json:"file_name"`
	MimeType        string `json:"mime_type"`
	JoplinID        string `json:"joplin_id"`
	ParentID        string `json:"parent_id"`
	ShareID         string `json:"share_id"`
	ItemType        int64  `json:"item_type"`
	IsEncrypted     int64  `json:"is_encrypted"`
	ClientUpdatedAt int64  `json:"client_updated_at"`
	OwnerID         string `json:"owner_id"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) UpsertSyncItem(ctx context.Context, arg UpsertSyncItemParams) (SyncItem, error) {
	row := q.db.QueryRowContext(ctx, upsertSyncItem,
		arg.ID,
		arg.FileName,
		arg.MimeType,
		arg.JoplinID,
		arg.ParentID,
		arg.ShareID,
		arg.ItemType,
		arg.IsEncrypted,
		arg.ClientUpdatedAt,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SyncItem
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.JoplinID,
		&i.ParentID,
		&i.ShareID,
		&i.ItemType,
		&i.IsEncrypted,
		&i.ClientUpdatedAt,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSyncItem = `-- name: UpsertUserSyncItem :one
INSERT INTO user_sync_items (
  user_id, sync_item_id, created_at, updated_at
) VALUES (
  ?, ?, ?, ?
)
ON CONFLICT(user_id, sync_item_id) DO UPDATE SET
  updated_at = excluded.updated_at
RETURNING id, user_id, sync_item_id, created_at, updated_at
`

type UpsertUserSyncItemParams struct {
	UserID     string `json:"user_id"`
	SyncItemID string `json:"sync_item_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertUserSyncItem(ctx context.Context, arg UpsertUserSyncItemParams) (UserSyncItem, error) {
	row := q.db.QueryRowContext(ctx, upsertUserSyncItem,
		arg.UserID,
		arg.SyncItemID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserSyncItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SyncItemID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
