// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id, user_id, auth_code, created_time, updated_time
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, user_id, auth_code, created_time, updated_time
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	AuthCode    string `json:"auth_code"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AuthCode,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthCode,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, password, is_admin, created_time, updated_time
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, email, password, is_admin, created_time, updated_time
`

type CreateUserParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	IsAdmin     int64  `json:"is_admin"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.IsAdmin,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const deleteItemByNameAndUser = `-- name: DeleteItemByNameAndUser :exec
DELETE FROM items
WHERE name = ? AND id IN (
  SELECT item_id FROM user_items WHERE user_id = ?
)
`

type DeleteItemByNameAndUserParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteItemByNameAndUser(ctx context.Context, arg DeleteItemByNameAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemByNameAndUser, arg.Name, arg.UserID)
	return err
}

const deleteKeyValue = `-- name: DeleteKeyValue :exec
DELETE FROM key_values
WHERE key = ?
`

func (q *Queries) DeleteKeyValue(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteKeyValue, key)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserItem = `-- name: DeleteUserItem :exec
DELETE FROM user_items
WHERE user_id = ? AND item_id = ?
`

type DeleteUserItemParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteUserItem(ctx context.Context, arg DeleteUserItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserItem, arg.UserID, arg.ItemID)
	return err
}

const getChangesByUser = `-- name: GetChangesByUser :many
SELECT counter, id, item_id, user_id, item_name, previous_share_id, item_type, type, created_time, updated_time FROM changes_2
WHERE user_id = ? AND counter > ?
ORDER BY counter ASC
LIMIT ?
`

type GetChangesByUserParams struct {
	UserID  string `json:"user_id"`
	Counter int64  `json:"counter"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) GetChangesByUser(ctx context.Context, arg GetChangesByUserParams) ([]Changes2, error) {
	rows, err := q.db.QueryContext(ctx, getChangesByUser, arg.UserID, arg.Counter, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Changes2
	for rows.Next() {
		var i Changes2
		if err := rows.Scan(
			&i.Counter,
			&i.ID,
			&i.ItemID,
			&i.UserID,
			&i.ItemName,
			&i.PreviousShareID,
			&i.ItemType,
			&i.Type,
			&i.CreatedTime,
			&i.UpdatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByNameAndUser = `-- name: GetItemByNameAndUser :one
SELECT items.id, items.name, items.mime_type, items.jop_id, items.jop_parent_id, items.jop_share_id, items.jop_type, items.jop_encryption_applied, items.jop_updated_time, items.owner_id, items.content_storage_id, items.created_time, items.updated_time FROM items
JOIN user_items ON items.id = user_items.item_id
WHERE items.name = ? AND user_items.user_id = ?
LIMIT 1
`

type GetItemByNameAndUserParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetItemByNameAndUser(ctx context.Context, arg GetItemByNameAndUserParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByNameAndUser, arg.Name, arg.UserID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.JopID,
		&i.JopParentID,
		&i.JopShareID,
		&i.JopType,
		&i.JopEncryptionApplied,
		&i.JopUpdatedTime,
		&i.OwnerID,
		&i.ContentStorageID,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getKeyValue = `-- name: GetKeyValue :one
SELECT id, "key", type, value FROM key_values
WHERE key = ? LIMIT 1
`

func (q *Queries) GetKeyValue(ctx context.Context, key string) (KeyValue, error) {
	row := q.db.QueryRowContext(ctx, getKeyValue, key)
	var i KeyValue
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Type,
		&i.Value,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, auth_code, created_time, updated_time FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthCode,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password, is_admin, created_time, updated_time FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, is_admin, created_time, updated_time FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const insertChange = `-- name: InsertChange :one
INSERT INTO changes_2 (
  id, item_id, user_id, item_name, previous_share_id, item_type, type, created_time, updated_time
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING counter, id, item_id, user_id, item_name, previous_share_id, item_type, type, created_time, updated_time
`

type InsertChangeParams struct {
	ID              string `json:"id"`
	ItemID          string `json:"item_id"`
	UserID          string `json:"user_id"`
	ItemName        string `json:"item_name"`
	PreviousShareID string `json:"previous_share_id"`
	ItemType        int64  `json:"item_type"`
	Type            int64  `json:"type"`
	CreatedTime     int64  `json:"created_time"`
	UpdatedTime     int64  `json:"updated_time"`
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (Changes2, error) {
	row := q.db.QueryRowContext(ctx, insertChange,
		arg.ID,
		arg.ItemID,
		arg.UserID,
		arg.ItemName,
		arg.PreviousShareID,
		arg.ItemType,
		arg.Type,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i Changes2
	err := row.Scan(
		&i.Counter,
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.ItemName,
		&i.PreviousShareID,
		&i.ItemType,
		&i.Type,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const listItemsByUser = `-- name: ListItemsByUser :many
SELECT items.id, items.name, items.mime_type, items.jop_id, items.jop_parent_id, items.jop_share_id, items.jop_type, items.jop_encryption_applied, items.jop_updated_time, items.owner_id, items.content_storage_id, items.created_time, items.updated_time FROM items
JOIN user_items ON items.id = user_items.item_id
WHERE user_items.user_id = ?
ORDER BY items.updated_time ASC
LIMIT ? OFFSET ?
`

type ListItemsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListItemsByUser(ctx context.Context, arg ListItemsByUserParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.JopID,
			&i.JopParentID,
			&i.JopShareID,
			&i.JopType,
			&i.JopEncryptionApplied,
			&i.JopUpdatedTime,
			&i.OwnerID,
			&i.ContentStorageID,
			&i.CreatedTime,
			&i.UpdatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeyValuesByType = `-- name: ListKeyValuesByType :many
SELECT id, "key", type, value FROM key_values
WHERE type = ?
`

func (q *Queries) ListKeyValuesByType(ctx context.Context, type_ int64) ([]KeyValue, error) {
	rows, err := q.db.QueryContext(ctx, listKeyValuesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyValue
	for rows.Next() {
		var i KeyValue
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKeyValue = `-- name: SetKeyValue :one
INSERT INTO key_values (
  key, type, value
) VALUES (
  ?, ?, ?
)
ON CONFLICT(key) DO UPDATE SET
  type = excluded.type,
  value = excluded.value
RETURNING id, "key", type, value
`

type SetKeyValueParams struct {
	Key   string `json:"key"`
	Type  int64  `json:"type"`
	Value string `json:"value"`
}

func (q *Queries) SetKeyValue(ctx context.Context, arg SetKeyValueParams) (KeyValue, error) {
	row := q.db.QueryRowContext(ctx, setKeyValue, arg.Key, arg.Type, arg.Value)
	var i KeyValue
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Type,
		&i.Value,
	)
	return i, err
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items (
  id, name, mime_type, jop_id, jop_parent_id, jop_share_id,
  jop_type, jop_encryption_applied, jop_updated_time, owner_id, content_storage_id,
  created_time, updated_time
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  mime_type = excluded.mime_type,
  jop_id = excluded.jop_id,
  jop_parent_id = excluded.jop_parent_id,
  jop_share_id = excluded.jop_share_id,
  jop_type = excluded.jop_type,
  jop_encryption_applied = excluded.jop_encryption_applied,
  jop_updated_time = excluded.jop_updated_time,
  owner_id = excluded.owner_id,
  content_storage_id = excluded.content_storage_id,
  updated_time = excluded.updated_time
RETURNING id, name, mime_type, jop_id, jop_parent_id, jop_share_id, jop_type, jop_encryption_applied, jop_updated_time, owner_id, content_storage_id, created_time, updated_time
`

type UpsertItemParams struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	MimeType             string `json:"mime_type"`
	JopID                string `json:"jop_id"`
	JopParentID          string `json:"jop_parent_id"`
	JopShareID           string `json:"jop_share_id"`
	JopType              int64  `json:"jop_type"`
	JopEncryptionApplied int64  `json:"jop_encryption_applied"`
	JopUpdatedTime       int64  `json:"jop_updated_time"`
	OwnerID              string `json:"owner_id"`
	ContentStorageID     int64  `json:"content_storage_id"`
	CreatedTime          int64  `json:"created_time"`
	UpdatedTime          int64  `json:"updated_time"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, upsertItem,
		arg.ID,
		arg.Name,
		arg.MimeType,
		arg.JopID,
		arg.JopParentID,
		arg.JopShareID,
		arg.JopType,
		arg.JopEncryptionApplied,
		arg.JopUpdatedTime,
		arg.OwnerID,
		arg.ContentStorageID,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.JopID,
		&i.JopParentID,
		&i.JopShareID,
		&i.JopType,
		&i.JopEncryptionApplied,
		&i.JopUpdatedTime,
		&i.OwnerID,
		&i.ContentStorageID,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const upsertUserItem = `-- name: UpsertUserItem :one
INSERT INTO user_items (
  user_id, item_id, created_time, updated_time
) VALUES (
  ?, ?, ?, ?
)
ON CONFLICT(user_id, item_id) DO UPDATE SET
  updated_time = excluded.updated_time
RETURNING id, user_id, item_id, created_time, updated_time
`

type UpsertUserItemParams struct {
	UserID      string `json:"user_id"`
	ItemID      string `json:"item_id"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

func (q *Queries) UpsertUserItem(ctx context.Context, arg UpsertUserItemParams) (UserItem, error) {
	row := q.db.QueryRowContext(ctx, upsertUserItem,
		arg.UserID,
		arg.ItemID,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i UserItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}
