// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id, user_id, auth_code, created_time, updated_time
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, user_id, auth_code, created_time, updated_time
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	AuthCode    string `json:"auth_code"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AuthCode,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthCode,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, password, full_name, is_admin, created_time, updated_time
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, email, password, full_name, is_admin, created_time, updated_time
`

type CreateUserParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	FullName    string `json:"full_name"`
	IsAdmin     int64  `json:"is_admin"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FullName,
		arg.IsAdmin,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.IsAdmin,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const deleteKeyValue = `-- name: DeleteKeyValue :exec
DELETE FROM key_values
WHERE key = ?
`

func (q *Queries) DeleteKeyValue(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteKeyValue, key)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getKeyValue = `-- name: GetKeyValue :one
SELECT id, "key", type, value FROM key_values
WHERE key = ? LIMIT 1
`

func (q *Queries) GetKeyValue(ctx context.Context, key string) (KeyValue, error) {
	row := q.db.QueryRowContext(ctx, getKeyValue, key)
	var i KeyValue
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Type,
		&i.Value,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, auth_code, created_time, updated_time FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthCode,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, full_name, is_admin, created_time, updated_time FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.IsAdmin,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const listKeyValuesByType = `-- name: ListKeyValuesByType :many
SELECT id, "key", type, value FROM key_values
WHERE type = ?
`

func (q *Queries) ListKeyValuesByType(ctx context.Context, type_ int64) ([]KeyValue, error) {
	rows, err := q.db.QueryContext(ctx, listKeyValuesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyValue
	for rows.Next() {
		var i KeyValue
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKeyValue = `-- name: SetKeyValue :one
INSERT INTO key_values (
  key, type, value
) VALUES (
  ?, ?, ?
)
ON CONFLICT(key) DO UPDATE SET
  type = excluded.type,
  value = excluded.value
RETURNING id, "key", type, value
`

type SetKeyValueParams struct {
	Key   string `json:"key"`
	Type  int64  `json:"type"`
	Value string `json:"value"`
}

func (q *Queries) SetKeyValue(ctx context.Context, arg SetKeyValueParams) (KeyValue, error) {
	row := q.db.QueryRowContext(ctx, setKeyValue, arg.Key, arg.Type, arg.Value)
	var i KeyValue
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Type,
		&i.Value,
	)
	return i, err
}
