// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package db

import (
	"context"
	"sync"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			CountUsersFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the CountUsers method")
//			},
//			CreateSessionFunc: func(ctx context.Context, arg CreateSessionParams) (Session, error) {
//				panic("mock out the CreateSession method")
//			},
//			CreateShareFunc: func(ctx context.Context, arg CreateShareParams) (Share, error) {
//				panic("mock out the CreateShare method")
//			},
//			CreateUserFunc: func(ctx context.Context, arg CreateUserParams) (User, error) {
//				panic("mock out the CreateUser method")
//			},
//			CreateUserShareFunc: func(ctx context.Context, arg CreateUserShareParams) (UserShare, error) {
//				panic("mock out the CreateUserShare method")
//			},
//			DeleteSessionFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteSession method")
//			},
//			DeleteSyncItemByFileNameAndUserFunc: func(ctx context.Context, arg DeleteSyncItemByFileNameAndUserParams) error {
//				panic("mock out the DeleteSyncItemByFileNameAndUser method")
//			},
//			DeleteSyncLockFunc: func(ctx context.Context, lockKey string) error {
//				panic("mock out the DeleteSyncLock method")
//			},
//			DeleteUserFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteUser method")
//			},
//			DeleteUserSyncItemFunc: func(ctx context.Context, arg DeleteUserSyncItemParams) error {
//				panic("mock out the DeleteUserSyncItem method")
//			},
//			GetDeltaEventsByUserFunc: func(ctx context.Context, arg GetDeltaEventsByUserParams) ([]DeltaEvent, error) {
//				panic("mock out the GetDeltaEventsByUser method")
//			},
//			GetInstanceStatsFunc: func(ctx context.Context) (GetInstanceStatsRow, error) {
//				panic("mock out the GetInstanceStats method")
//			},
//			GetSessionFunc: func(ctx context.Context, id string) (Session, error) {
//				panic("mock out the GetSession method")
//			},
//			GetSyncItemByFileNameAndUserFunc: func(ctx context.Context, arg GetSyncItemByFileNameAndUserParams) (SyncItem, error) {
//				panic("mock out the GetSyncItemByFileNameAndUser method")
//			},
//			GetSyncLockFunc: func(ctx context.Context, lockKey string) (SyncLock, error) {
//				panic("mock out the GetSyncLock method")
//			},
//			GetUserFunc: func(ctx context.Context, id string) (User, error) {
//				panic("mock out the GetUser method")
//			},
//			GetUserByEmailFunc: func(ctx context.Context, email string) (User, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserStatsFunc: func(ctx context.Context) ([]GetUserStatsRow, error) {
//				panic("mock out the GetUserStats method")
//			},
//			InsertDeltaEventFunc: func(ctx context.Context, arg InsertDeltaEventParams) (DeltaEvent, error) {
//				panic("mock out the InsertDeltaEvent method")
//			},
//			InsertShareTombstonesForDeletedUserFunc: func(ctx context.Context, arg InsertShareTombstonesForDeletedUserParams) error {
//				panic("mock out the InsertShareTombstonesForDeletedUser method")
//			},
//			ListSyncItemsByUserFunc: func(ctx context.Context, arg ListSyncItemsByUserParams) ([]SyncItem, error) {
//				panic("mock out the ListSyncItemsByUser method")
//			},
//			ListSyncLocksByTypeFunc: func(ctx context.Context, lockType int64) ([]SyncLock, error) {
//				panic("mock out the ListSyncLocksByType method")
//			},
//			ListUsersFunc: func(ctx context.Context) ([]User, error) {
//				panic("mock out the ListUsers method")
//			},
//			SetSyncLockFunc: func(ctx context.Context, arg SetSyncLockParams) (SyncLock, error) {
//				panic("mock out the SetSyncLock method")
//			},
//			UpsertSyncItemFunc: func(ctx context.Context, arg UpsertSyncItemParams) (SyncItem, error) {
//				panic("mock out the UpsertSyncItem method")
//			},
//			UpsertUserSyncItemFunc: func(ctx context.Context, arg UpsertUserSyncItemParams) (UserSyncItem, error) {
//				panic("mock out the UpsertUserSyncItem method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// CountUsersFunc mocks the CountUsers method.
	CountUsersFunc func(ctx context.Context) (int64, error)

	// CreateSessionFunc mocks the CreateSession method.
	CreateSessionFunc func(ctx context.Context, arg CreateSessionParams) (Session, error)

	// CreateShareFunc mocks the CreateShare method.
	CreateShareFunc func(ctx context.Context, arg CreateShareParams) (Share, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, arg CreateUserParams) (User, error)

	// CreateUserShareFunc mocks the CreateUserShare method.
	CreateUserShareFunc func(ctx context.Context, arg CreateUserShareParams) (UserShare, error)

	// DeleteSessionFunc mocks the DeleteSession method.
	DeleteSessionFunc func(ctx context.Context, id string) error

	// DeleteSyncItemByFileNameAndUserFunc mocks the DeleteSyncItemByFileNameAndUser method.
	DeleteSyncItemByFileNameAndUserFunc func(ctx context.Context, arg DeleteSyncItemByFileNameAndUserParams) error

	// DeleteSyncLockFunc mocks the DeleteSyncLock method.
	DeleteSyncLockFunc func(ctx context.Context, lockKey string) error

	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, id string) error

	// DeleteUserSyncItemFunc mocks the DeleteUserSyncItem method.
	DeleteUserSyncItemFunc func(ctx context.Context, arg DeleteUserSyncItemParams) error

	// GetDeltaEventsByUserFunc mocks the GetDeltaEventsByUser method.
	GetDeltaEventsByUserFunc func(ctx context.Context, arg GetDeltaEventsByUserParams) ([]DeltaEvent, error)

	// GetInstanceStatsFunc mocks the GetInstanceStats method.
	GetInstanceStatsFunc func(ctx context.Context) (GetInstanceStatsRow, error)

	// GetSessionFunc mocks the GetSession method.
	GetSessionFunc func(ctx context.Context, id string) (Session, error)

	// GetSyncItemByFileNameAndUserFunc mocks the GetSyncItemByFileNameAndUser method.
	GetSyncItemByFileNameAndUserFunc func(ctx context.Context, arg GetSyncItemByFileNameAndUserParams) (SyncItem, error)

	// GetSyncLockFunc mocks the GetSyncLock method.
	GetSyncLockFunc func(ctx context.Context, lockKey string) (SyncLock, error)

	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(ctx context.Context, id string) (User, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(ctx context.Context, email string) (User, error)

	// GetUserStatsFunc mocks the GetUserStats method.
	GetUserStatsFunc func(ctx context.Context) ([]GetUserStatsRow, error)

	// InsertDeltaEventFunc mocks the InsertDeltaEvent method.
	InsertDeltaEventFunc func(ctx context.Context, arg InsertDeltaEventParams) (DeltaEvent, error)

	// InsertShareTombstonesForDeletedUserFunc mocks the InsertShareTombstonesForDeletedUser method.
	InsertShareTombstonesForDeletedUserFunc func(ctx context.Context, arg InsertShareTombstonesForDeletedUserParams) error

	// ListSyncItemsByUserFunc mocks the ListSyncItemsByUser method.
	ListSyncItemsByUserFunc func(ctx context.Context, arg ListSyncItemsByUserParams) ([]SyncItem, error)

	// ListSyncLocksByTypeFunc mocks the ListSyncLocksByType method.
	ListSyncLocksByTypeFunc func(ctx context.Context, lockType int64) ([]SyncLock, error)

	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context) ([]User, error)

	// SetSyncLockFunc mocks the SetSyncLock method.
	SetSyncLockFunc func(ctx context.Context, arg SetSyncLockParams) (SyncLock, error)

	// UpsertSyncItemFunc mocks the UpsertSyncItem method.
	UpsertSyncItemFunc func(ctx context.Context, arg UpsertSyncItemParams) (SyncItem, error)

	// UpsertUserSyncItemFunc mocks the UpsertUserSyncItem method.
	UpsertUserSyncItemFunc func(ctx context.Context, arg UpsertUserSyncItemParams) (UserSyncItem, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountUsers holds details about calls to the CountUsers method.
		CountUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateSession holds details about calls to the CreateSession method.
		CreateSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg CreateSessionParams
		}
		// CreateShare holds details about calls to the CreateShare method.
		CreateShare []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg CreateShareParams
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg CreateUserParams
		}
		// CreateUserShare holds details about calls to the CreateUserShare method.
		CreateUserShare []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg CreateUserShareParams
		}
		// DeleteSession holds details about calls to the DeleteSession method.
		DeleteSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// DeleteSyncItemByFileNameAndUser holds details about calls to the DeleteSyncItemByFileNameAndUser method.
		DeleteSyncItemByFileNameAndUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg DeleteSyncItemByFileNameAndUserParams
		}
		// DeleteSyncLock holds details about calls to the DeleteSyncLock method.
		DeleteSyncLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LockKey is the lockKey argument value.
			LockKey string
		}
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// DeleteUserSyncItem holds details about calls to the DeleteUserSyncItem method.
		DeleteUserSyncItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg DeleteUserSyncItemParams
		}
		// GetDeltaEventsByUser holds details about calls to the GetDeltaEventsByUser method.
		GetDeltaEventsByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg GetDeltaEventsByUserParams
		}
		// GetInstanceStats holds details about calls to the GetInstanceStats method.
		GetInstanceStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSession holds details about calls to the GetSession method.
		GetSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetSyncItemByFileNameAndUser holds details about calls to the GetSyncItemByFileNameAndUser method.
		GetSyncItemByFileNameAndUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg GetSyncItemByFileNameAndUserParams
		}
		// GetSyncLock holds details about calls to the GetSyncLock method.
		GetSyncLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LockKey is the lockKey argument value.
			LockKey string
		}
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetUserStats holds details about calls to the GetUserStats method.
		GetUserStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// InsertDeltaEvent holds details about calls to the InsertDeltaEvent method.
		InsertDeltaEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg InsertDeltaEventParams
		}
		// InsertShareTombstonesForDeletedUser holds details about calls to the InsertShareTombstonesForDeletedUser method.
		InsertShareTombstonesForDeletedUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg InsertShareTombstonesForDeletedUserParams
		}
		// ListSyncItemsByUser holds details about calls to the ListSyncItemsByUser method.
		ListSyncItemsByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg ListSyncItemsByUserParams
		}
		// ListSyncLocksByType holds details about calls to the ListSyncLocksByType method.
		ListSyncLocksByType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LockType is the lockType argument value.
			LockType int64
		}
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SetSyncLock holds details about calls to the SetSyncLock method.
		SetSyncLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg SetSyncLockParams
		}
		// UpsertSyncItem holds details about calls to the UpsertSyncItem method.
		UpsertSyncItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpsertSyncItemParams
		}
		// UpsertUserSyncItem holds details about calls to the UpsertUserSyncItem method.
		UpsertUserSyncItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg UpsertUserSyncItemParams
		}
	}
	lockCountUsers                          sync.RWMutex
	lockCreateSession                       sync.RWMutex
	lockCreateShare                         sync.RWMutex
	lockCreateUser                          sync.RWMutex
	lockCreateUserShare                     sync.RWMutex
	lockDeleteSession                       sync.RWMutex
	lockDeleteSyncItemByFileNameAndUser     sync.RWMutex
	lockDeleteSyncLock                      sync.RWMutex
	lockDeleteUser                          sync.RWMutex
	lockDeleteUserSyncItem                  sync.RWMutex
	lockGetDeltaEventsByUser                sync.RWMutex
	lockGetInstanceStats                    sync.RWMutex
	lockGetSession                          sync.RWMutex
	lockGetSyncItemByFileNameAndUser        sync.RWMutex
	lockGetSyncLock                         sync.RWMutex
	lockGetUser                             sync.RWMutex
	lockGetUserByEmail                      sync.RWMutex
	lockGetUserStats                        sync.RWMutex
	lockInsertDeltaEvent                    sync.RWMutex
	lockInsertShareTombstonesForDeletedUser sync.RWMutex
	lockListSyncItemsByUser                 sync.RWMutex
	lockListSyncLocksByType                 sync.RWMutex
	lockListUsers                           sync.RWMutex
	lockSetSyncLock                         sync.RWMutex
	lockUpsertSyncItem                      sync.RWMutex
	lockUpsertUserSyncItem                  sync.RWMutex
}

// CountUsers calls CountUsersFunc.
func (mock *QuerierMock) CountUsers(ctx context.Context) (int64, error) {
	if mock.CountUsersFunc == nil {
		panic("QuerierMock.CountUsersFunc: method is nil but Querier.CountUsers was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountUsers.Lock()
	mock.calls.CountUsers = append(mock.calls.CountUsers, callInfo)
	mock.lockCountUsers.Unlock()
	return mock.CountUsersFunc(ctx)
}

// CountUsersCalls gets all the calls that were made to CountUsers.
// Check the length with:
//
//	len(mockedQuerier.CountUsersCalls())
func (mock *QuerierMock) CountUsersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountUsers.RLock()
	calls = mock.calls.CountUsers
	mock.lockCountUsers.RUnlock()
	return calls
}

// CreateSession calls CreateSessionFunc.
func (mock *QuerierMock) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	if mock.CreateSessionFunc == nil {
		panic("QuerierMock.CreateSessionFunc: method is nil but Querier.CreateSession was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg CreateSessionParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateSession.Lock()
	mock.calls.CreateSession = append(mock.calls.CreateSession, callInfo)
	mock.lockCreateSession.Unlock()
	return mock.CreateSessionFunc(ctx, arg)
}

// CreateSessionCalls gets all the calls that were made to CreateSession.
// Check the length with:
//
//	len(mockedQuerier.CreateSessionCalls())
func (mock *QuerierMock) CreateSessionCalls() []struct {
	Ctx context.Context
	Arg CreateSessionParams
} {
	var calls []struct {
		Ctx context.Context
		Arg CreateSessionParams
	}
	mock.lockCreateSession.RLock()
	calls = mock.calls.CreateSession
	mock.lockCreateSession.RUnlock()
	return calls
}

// CreateShare calls CreateShareFunc.
func (mock *QuerierMock) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	if mock.CreateShareFunc == nil {
		panic("QuerierMock.CreateShareFunc: method is nil but Querier.CreateShare was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg CreateShareParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateShare.Lock()
	mock.calls.CreateShare = append(mock.calls.CreateShare, callInfo)
	mock.lockCreateShare.Unlock()
	return mock.CreateShareFunc(ctx, arg)
}

// CreateShareCalls gets all the calls that were made to CreateShare.
// Check the length with:
//
//	len(mockedQuerier.CreateShareCalls())
func (mock *QuerierMock) CreateShareCalls() []struct {
	Ctx context.Context
	Arg CreateShareParams
} {
	var calls []struct {
		Ctx context.Context
		Arg CreateShareParams
	}
	mock.lockCreateShare.RLock()
	calls = mock.calls.CreateShare
	mock.lockCreateShare.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *QuerierMock) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	if mock.CreateUserFunc == nil {
		panic("QuerierMock.CreateUserFunc: method is nil but Querier.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg CreateUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, arg)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedQuerier.CreateUserCalls())
func (mock *QuerierMock) CreateUserCalls() []struct {
	Ctx context.Context
	Arg CreateUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg CreateUserParams
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// CreateUserShare calls CreateUserShareFunc.
func (mock *QuerierMock) CreateUserShare(ctx context.Context, arg CreateUserShareParams) (UserShare, error) {
	if mock.CreateUserShareFunc == nil {
		panic("QuerierMock.CreateUserShareFunc: method is nil but Querier.CreateUserShare was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg CreateUserShareParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateUserShare.Lock()
	mock.calls.CreateUserShare = append(mock.calls.CreateUserShare, callInfo)
	mock.lockCreateUserShare.Unlock()
	return mock.CreateUserShareFunc(ctx, arg)
}

// CreateUserShareCalls gets all the calls that were made to CreateUserShare.
// Check the length with:
//
//	len(mockedQuerier.CreateUserShareCalls())
func (mock *QuerierMock) CreateUserShareCalls() []struct {
	Ctx context.Context
	Arg CreateUserShareParams
} {
	var calls []struct {
		Ctx context.Context
		Arg CreateUserShareParams
	}
	mock.lockCreateUserShare.RLock()
	calls = mock.calls.CreateUserShare
	mock.lockCreateUserShare.RUnlock()
	return calls
}

// DeleteSession calls DeleteSessionFunc.
func (mock *QuerierMock) DeleteSession(ctx context.Context, id string) error {
	if mock.DeleteSessionFunc == nil {
		panic("QuerierMock.DeleteSessionFunc: method is nil but Querier.DeleteSession was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteSession.Lock()
	mock.calls.DeleteSession = append(mock.calls.DeleteSession, callInfo)
	mock.lockDeleteSession.Unlock()
	return mock.DeleteSessionFunc(ctx, id)
}

// DeleteSessionCalls gets all the calls that were made to DeleteSession.
// Check the length with:
//
//	len(mockedQuerier.DeleteSessionCalls())
func (mock *QuerierMock) DeleteSessionCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteSession.RLock()
	calls = mock.calls.DeleteSession
	mock.lockDeleteSession.RUnlock()
	return calls
}

// DeleteSyncItemByFileNameAndUser calls DeleteSyncItemByFileNameAndUserFunc.
func (mock *QuerierMock) DeleteSyncItemByFileNameAndUser(ctx context.Context, arg DeleteSyncItemByFileNameAndUserParams) error {
	if mock.DeleteSyncItemByFileNameAndUserFunc == nil {
		panic("QuerierMock.DeleteSyncItemByFileNameAndUserFunc: method is nil but Querier.DeleteSyncItemByFileNameAndUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg DeleteSyncItemByFileNameAndUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteSyncItemByFileNameAndUser.Lock()
	mock.calls.DeleteSyncItemByFileNameAndUser = append(mock.calls.DeleteSyncItemByFileNameAndUser, callInfo)
	mock.lockDeleteSyncItemByFileNameAndUser.Unlock()
	return mock.DeleteSyncItemByFileNameAndUserFunc(ctx, arg)
}

// DeleteSyncItemByFileNameAndUserCalls gets all the calls that were made to DeleteSyncItemByFileNameAndUser.
// Check the length with:
//
//	len(mockedQuerier.DeleteSyncItemByFileNameAndUserCalls())
func (mock *QuerierMock) DeleteSyncItemByFileNameAndUserCalls() []struct {
	Ctx context.Context
	Arg DeleteSyncItemByFileNameAndUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg DeleteSyncItemByFileNameAndUserParams
	}
	mock.lockDeleteSyncItemByFileNameAndUser.RLock()
	calls = mock.calls.DeleteSyncItemByFileNameAndUser
	mock.lockDeleteSyncItemByFileNameAndUser.RUnlock()
	return calls
}

// DeleteSyncLock calls DeleteSyncLockFunc.
func (mock *QuerierMock) DeleteSyncLock(ctx context.Context, lockKey string) error {
	if mock.DeleteSyncLockFunc == nil {
		panic("QuerierMock.DeleteSyncLockFunc: method is nil but Querier.DeleteSyncLock was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		LockKey string
	}{
		Ctx:     ctx,
		LockKey: lockKey,
	}
	mock.lockDeleteSyncLock.Lock()
	mock.calls.DeleteSyncLock = append(mock.calls.DeleteSyncLock, callInfo)
	mock.lockDeleteSyncLock.Unlock()
	return mock.DeleteSyncLockFunc(ctx, lockKey)
}

// DeleteSyncLockCalls gets all the calls that were made to DeleteSyncLock.
// Check the length with:
//
//	len(mockedQuerier.DeleteSyncLockCalls())
func (mock *QuerierMock) DeleteSyncLockCalls() []struct {
	Ctx     context.Context
	LockKey string
} {
	var calls []struct {
		Ctx     context.Context
		LockKey string
	}
	mock.lockDeleteSyncLock.RLock()
	calls = mock.calls.DeleteSyncLock
	mock.lockDeleteSyncLock.RUnlock()
	return calls
}

// DeleteUser calls DeleteUserFunc.
func (mock *QuerierMock) DeleteUser(ctx context.Context, id string) error {
	if mock.DeleteUserFunc == nil {
		panic("QuerierMock.DeleteUserFunc: method is nil but Querier.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, id)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedQuerier.DeleteUserCalls())
func (mock *QuerierMock) DeleteUserCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// DeleteUserSyncItem calls DeleteUserSyncItemFunc.
func (mock *QuerierMock) DeleteUserSyncItem(ctx context.Context, arg DeleteUserSyncItemParams) error {
	if mock.DeleteUserSyncItemFunc == nil {
		panic("QuerierMock.DeleteUserSyncItemFunc: method is nil but Querier.DeleteUserSyncItem was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg DeleteUserSyncItemParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteUserSyncItem.Lock()
	mock.calls.DeleteUserSyncItem = append(mock.calls.DeleteUserSyncItem, callInfo)
	mock.lockDeleteUserSyncItem.Unlock()
	return mock.DeleteUserSyncItemFunc(ctx, arg)
}

// DeleteUserSyncItemCalls gets all the calls that were made to DeleteUserSyncItem.
// Check the length with:
//
//	len(mockedQuerier.DeleteUserSyncItemCalls())
func (mock *QuerierMock) DeleteUserSyncItemCalls() []struct {
	Ctx context.Context
	Arg DeleteUserSyncItemParams
} {
	var calls []struct {
		Ctx context.Context
		Arg DeleteUserSyncItemParams
	}
	mock.lockDeleteUserSyncItem.RLock()
	calls = mock.calls.DeleteUserSyncItem
	mock.lockDeleteUserSyncItem.RUnlock()
	return calls
}

// GetDeltaEventsByUser calls GetDeltaEventsByUserFunc.
func (mock *QuerierMock) GetDeltaEventsByUser(ctx context.Context, arg GetDeltaEventsByUserParams) ([]DeltaEvent, error) {
	if mock.GetDeltaEventsByUserFunc == nil {
		panic("QuerierMock.GetDeltaEventsByUserFunc: method is nil but Querier.GetDeltaEventsByUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg GetDeltaEventsByUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetDeltaEventsByUser.Lock()
	mock.calls.GetDeltaEventsByUser = append(mock.calls.GetDeltaEventsByUser, callInfo)
	mock.lockGetDeltaEventsByUser.Unlock()
	return mock.GetDeltaEventsByUserFunc(ctx, arg)
}

// GetDeltaEventsByUserCalls gets all the calls that were made to GetDeltaEventsByUser.
// Check the length with:
//
//	len(mockedQuerier.GetDeltaEventsByUserCalls())
func (mock *QuerierMock) GetDeltaEventsByUserCalls() []struct {
	Ctx context.Context
	Arg GetDeltaEventsByUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg GetDeltaEventsByUserParams
	}
	mock.lockGetDeltaEventsByUser.RLock()
	calls = mock.calls.GetDeltaEventsByUser
	mock.lockGetDeltaEventsByUser.RUnlock()
	return calls
}

// GetInstanceStats calls GetInstanceStatsFunc.
func (mock *QuerierMock) GetInstanceStats(ctx context.Context) (GetInstanceStatsRow, error) {
	if mock.GetInstanceStatsFunc == nil {
		panic("QuerierMock.GetInstanceStatsFunc: method is nil but Querier.GetInstanceStats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetInstanceStats.Lock()
	mock.calls.GetInstanceStats = append(mock.calls.GetInstanceStats, callInfo)
	mock.lockGetInstanceStats.Unlock()
	return mock.GetInstanceStatsFunc(ctx)
}

// GetInstanceStatsCalls gets all the calls that were made to GetInstanceStats.
// Check the length with:
//
//	len(mockedQuerier.GetInstanceStatsCalls())
func (mock *QuerierMock) GetInstanceStatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetInstanceStats.RLock()
	calls = mock.calls.GetInstanceStats
	mock.lockGetInstanceStats.RUnlock()
	return calls
}

// GetSession calls GetSessionFunc.
func (mock *QuerierMock) GetSession(ctx context.Context, id string) (Session, error) {
	if mock.GetSessionFunc == nil {
		panic("QuerierMock.GetSessionFunc: method is nil but Querier.GetSession was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSession.Lock()
	mock.calls.GetSession = append(mock.calls.GetSession, callInfo)
	mock.lockGetSession.Unlock()
	return mock.GetSessionFunc(ctx, id)
}

// GetSessionCalls gets all the calls that were made to GetSession.
// Check the length with:
//
//	len(mockedQuerier.GetSessionCalls())
func (mock *QuerierMock) GetSessionCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetSession.RLock()
	calls = mock.calls.GetSession
	mock.lockGetSession.RUnlock()
	return calls
}

// GetSyncItemByFileNameAndUser calls GetSyncItemByFileNameAndUserFunc.
func (mock *QuerierMock) GetSyncItemByFileNameAndUser(ctx context.Context, arg GetSyncItemByFileNameAndUserParams) (SyncItem, error) {
	if mock.GetSyncItemByFileNameAndUserFunc == nil {
		panic("QuerierMock.GetSyncItemByFileNameAndUserFunc: method is nil but Querier.GetSyncItemByFileNameAndUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg GetSyncItemByFileNameAndUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetSyncItemByFileNameAndUser.Lock()
	mock.calls.GetSyncItemByFileNameAndUser = append(mock.calls.GetSyncItemByFileNameAndUser, callInfo)
	mock.lockGetSyncItemByFileNameAndUser.Unlock()
	return mock.GetSyncItemByFileNameAndUserFunc(ctx, arg)
}

// GetSyncItemByFileNameAndUserCalls gets all the calls that were made to GetSyncItemByFileNameAndUser.
// Check the length with:
//
//	len(mockedQuerier.GetSyncItemByFileNameAndUserCalls())
func (mock *QuerierMock) GetSyncItemByFileNameAndUserCalls() []struct {
	Ctx context.Context
	Arg GetSyncItemByFileNameAndUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg GetSyncItemByFileNameAndUserParams
	}
	mock.lockGetSyncItemByFileNameAndUser.RLock()
	calls = mock.calls.GetSyncItemByFileNameAndUser
	mock.lockGetSyncItemByFileNameAndUser.RUnlock()
	return calls
}

// GetSyncLock calls GetSyncLockFunc.
func (mock *QuerierMock) GetSyncLock(ctx context.Context, lockKey string) (SyncLock, error) {
	if mock.GetSyncLockFunc == nil {
		panic("QuerierMock.GetSyncLockFunc: method is nil but Querier.GetSyncLock was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		LockKey string
	}{
		Ctx:     ctx,
		LockKey: lockKey,
	}
	mock.lockGetSyncLock.Lock()
	mock.calls.GetSyncLock = append(mock.calls.GetSyncLock, callInfo)
	mock.lockGetSyncLock.Unlock()
	return mock.GetSyncLockFunc(ctx, lockKey)
}

// GetSyncLockCalls gets all the calls that were made to GetSyncLock.
// Check the length with:
//
//	len(mockedQuerier.GetSyncLockCalls())
func (mock *QuerierMock) GetSyncLockCalls() []struct {
	Ctx     context.Context
	LockKey string
} {
	var calls []struct {
		Ctx     context.Context
		LockKey string
	}
	mock.lockGetSyncLock.RLock()
	calls = mock.calls.GetSyncLock
	mock.lockGetSyncLock.RUnlock()
	return calls
}

// GetUser calls GetUserFunc.
func (mock *QuerierMock) GetUser(ctx context.Context, id string) (User, error) {
	if mock.GetUserFunc == nil {
		panic("QuerierMock.GetUserFunc: method is nil but Querier.GetUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	mock.lockGetUser.Unlock()
	return mock.GetUserFunc(ctx, id)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//
//	len(mockedQuerier.GetUserCalls())
func (mock *QuerierMock) GetUserCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetUser.RLock()
	calls = mock.calls.GetUser
	mock.lockGetUser.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *QuerierMock) GetUserByEmail(ctx context.Context, email string) (User, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("QuerierMock.GetUserByEmailFunc: method is nil but Querier.GetUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(ctx, email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedQuerier.GetUserByEmailCalls())
func (mock *QuerierMock) GetUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserStats calls GetUserStatsFunc.
func (mock *QuerierMock) GetUserStats(ctx context.Context) ([]GetUserStatsRow, error) {
	if mock.GetUserStatsFunc == nil {
		panic("QuerierMock.GetUserStatsFunc: method is nil but Querier.GetUserStats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetUserStats.Lock()
	mock.calls.GetUserStats = append(mock.calls.GetUserStats, callInfo)
	mock.lockGetUserStats.Unlock()
	return mock.GetUserStatsFunc(ctx)
}

// GetUserStatsCalls gets all the calls that were made to GetUserStats.
// Check the length with:
//
//	len(mockedQuerier.GetUserStatsCalls())
func (mock *QuerierMock) GetUserStatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetUserStats.RLock()
	calls = mock.calls.GetUserStats
	mock.lockGetUserStats.RUnlock()
	return calls
}

// InsertDeltaEvent calls InsertDeltaEventFunc.
func (mock *QuerierMock) InsertDeltaEvent(ctx context.Context, arg InsertDeltaEventParams) (DeltaEvent, error) {
	if mock.InsertDeltaEventFunc == nil {
		panic("QuerierMock.InsertDeltaEventFunc: method is nil but Querier.InsertDeltaEvent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg InsertDeltaEventParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertDeltaEvent.Lock()
	mock.calls.InsertDeltaEvent = append(mock.calls.InsertDeltaEvent, callInfo)
	mock.lockInsertDeltaEvent.Unlock()
	return mock.InsertDeltaEventFunc(ctx, arg)
}

// InsertDeltaEventCalls gets all the calls that were made to InsertDeltaEvent.
// Check the length with:
//
//	len(mockedQuerier.InsertDeltaEventCalls())
func (mock *QuerierMock) InsertDeltaEventCalls() []struct {
	Ctx context.Context
	Arg InsertDeltaEventParams
} {
	var calls []struct {
		Ctx context.Context
		Arg InsertDeltaEventParams
	}
	mock.lockInsertDeltaEvent.RLock()
	calls = mock.calls.InsertDeltaEvent
	mock.lockInsertDeltaEvent.RUnlock()
	return calls
}

// InsertShareTombstonesForDeletedUser calls InsertShareTombstonesForDeletedUserFunc.
func (mock *QuerierMock) InsertShareTombstonesForDeletedUser(ctx context.Context, arg InsertShareTombstonesForDeletedUserParams) error {
	if mock.InsertShareTombstonesForDeletedUserFunc == nil {
		panic("QuerierMock.InsertShareTombstonesForDeletedUserFunc: method is nil but Querier.InsertShareTombstonesForDeletedUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg InsertShareTombstonesForDeletedUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertShareTombstonesForDeletedUser.Lock()
	mock.calls.InsertShareTombstonesForDeletedUser = append(mock.calls.InsertShareTombstonesForDeletedUser, callInfo)
	mock.lockInsertShareTombstonesForDeletedUser.Unlock()
	return mock.InsertShareTombstonesForDeletedUserFunc(ctx, arg)
}

// InsertShareTombstonesForDeletedUserCalls gets all the calls that were made to InsertShareTombstonesForDeletedUser.
// Check the length with:
//
//	len(mockedQuerier.InsertShareTombstonesForDeletedUserCalls())
func (mock *QuerierMock) InsertShareTombstonesForDeletedUserCalls() []struct {
	Ctx context.Context
	Arg InsertShareTombstonesForDeletedUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg InsertShareTombstonesForDeletedUserParams
	}
	mock.lockInsertShareTombstonesForDeletedUser.RLock()
	calls = mock.calls.InsertShareTombstonesForDeletedUser
	mock.lockInsertShareTombstonesForDeletedUser.RUnlock()
	return calls
}

// ListSyncItemsByUser calls ListSyncItemsByUserFunc.
func (mock *QuerierMock) ListSyncItemsByUser(ctx context.Context, arg ListSyncItemsByUserParams) ([]SyncItem, error) {
	if mock.ListSyncItemsByUserFunc == nil {
		panic("QuerierMock.ListSyncItemsByUserFunc: method is nil but Querier.ListSyncItemsByUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg ListSyncItemsByUserParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockListSyncItemsByUser.Lock()
	mock.calls.ListSyncItemsByUser = append(mock.calls.ListSyncItemsByUser, callInfo)
	mock.lockListSyncItemsByUser.Unlock()
	return mock.ListSyncItemsByUserFunc(ctx, arg)
}

// ListSyncItemsByUserCalls gets all the calls that were made to ListSyncItemsByUser.
// Check the length with:
//
//	len(mockedQuerier.ListSyncItemsByUserCalls())
func (mock *QuerierMock) ListSyncItemsByUserCalls() []struct {
	Ctx context.Context
	Arg ListSyncItemsByUserParams
} {
	var calls []struct {
		Ctx context.Context
		Arg ListSyncItemsByUserParams
	}
	mock.lockListSyncItemsByUser.RLock()
	calls = mock.calls.ListSyncItemsByUser
	mock.lockListSyncItemsByUser.RUnlock()
	return calls
}

// ListSyncLocksByType calls ListSyncLocksByTypeFunc.
func (mock *QuerierMock) ListSyncLocksByType(ctx context.Context, lockType int64) ([]SyncLock, error) {
	if mock.ListSyncLocksByTypeFunc == nil {
		panic("QuerierMock.ListSyncLocksByTypeFunc: method is nil but Querier.ListSyncLocksByType was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		LockType int64
	}{
		Ctx:      ctx,
		LockType: lockType,
	}
	mock.lockListSyncLocksByType.Lock()
	mock.calls.ListSyncLocksByType = append(mock.calls.ListSyncLocksByType, callInfo)
	mock.lockListSyncLocksByType.Unlock()
	return mock.ListSyncLocksByTypeFunc(ctx, lockType)
}

// ListSyncLocksByTypeCalls gets all the calls that were made to ListSyncLocksByType.
// Check the length with:
//
//	len(mockedQuerier.ListSyncLocksByTypeCalls())
func (mock *QuerierMock) ListSyncLocksByTypeCalls() []struct {
	Ctx      context.Context
	LockType int64
} {
	var calls []struct {
		Ctx      context.Context
		LockType int64
	}
	mock.lockListSyncLocksByType.RLock()
	calls = mock.calls.ListSyncLocksByType
	mock.lockListSyncLocksByType.RUnlock()
	return calls
}

// ListUsers calls ListUsersFunc.
func (mock *QuerierMock) ListUsers(ctx context.Context) ([]User, error) {
	if mock.ListUsersFunc == nil {
		panic("QuerierMock.ListUsersFunc: method is nil but Querier.ListUsers was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockedQuerier.ListUsersCalls())
func (mock *QuerierMock) ListUsersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}

// SetSyncLock calls SetSyncLockFunc.
func (mock *QuerierMock) SetSyncLock(ctx context.Context, arg SetSyncLockParams) (SyncLock, error) {
	if mock.SetSyncLockFunc == nil {
		panic("QuerierMock.SetSyncLockFunc: method is nil but Querier.SetSyncLock was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg SetSyncLockParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSetSyncLock.Lock()
	mock.calls.SetSyncLock = append(mock.calls.SetSyncLock, callInfo)
	mock.lockSetSyncLock.Unlock()
	return mock.SetSyncLockFunc(ctx, arg)
}

// SetSyncLockCalls gets all the calls that were made to SetSyncLock.
// Check the length with:
//
//	len(mockedQuerier.SetSyncLockCalls())
func (mock *QuerierMock) SetSyncLockCalls() []struct {
	Ctx context.Context
	Arg SetSyncLockParams
} {
	var calls []struct {
		Ctx context.Context
		Arg SetSyncLockParams
	}
	mock.lockSetSyncLock.RLock()
	calls = mock.calls.SetSyncLock
	mock.lockSetSyncLock.RUnlock()
	return calls
}

// UpsertSyncItem calls UpsertSyncItemFunc.
func (mock *QuerierMock) UpsertSyncItem(ctx context.Context, arg UpsertSyncItemParams) (SyncItem, error) {
	if mock.UpsertSyncItemFunc == nil {
		panic("QuerierMock.UpsertSyncItemFunc: method is nil but Querier.UpsertSyncItem was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpsertSyncItemParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertSyncItem.Lock()
	mock.calls.UpsertSyncItem = append(mock.calls.UpsertSyncItem, callInfo)
	mock.lockUpsertSyncItem.Unlock()
	return mock.UpsertSyncItemFunc(ctx, arg)
}

// UpsertSyncItemCalls gets all the calls that were made to UpsertSyncItem.
// Check the length with:
//
//	len(mockedQuerier.UpsertSyncItemCalls())
func (mock *QuerierMock) UpsertSyncItemCalls() []struct {
	Ctx context.Context
	Arg UpsertSyncItemParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpsertSyncItemParams
	}
	mock.lockUpsertSyncItem.RLock()
	calls = mock.calls.UpsertSyncItem
	mock.lockUpsertSyncItem.RUnlock()
	return calls
}

// UpsertUserSyncItem calls UpsertUserSyncItemFunc.
func (mock *QuerierMock) UpsertUserSyncItem(ctx context.Context, arg UpsertUserSyncItemParams) (UserSyncItem, error) {
	if mock.UpsertUserSyncItemFunc == nil {
		panic("QuerierMock.UpsertUserSyncItemFunc: method is nil but Querier.UpsertUserSyncItem was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg UpsertUserSyncItemParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertUserSyncItem.Lock()
	mock.calls.UpsertUserSyncItem = append(mock.calls.UpsertUserSyncItem, callInfo)
	mock.lockUpsertUserSyncItem.Unlock()
	return mock.UpsertUserSyncItemFunc(ctx, arg)
}

// UpsertUserSyncItemCalls gets all the calls that were made to UpsertUserSyncItem.
// Check the length with:
//
//	len(mockedQuerier.UpsertUserSyncItemCalls())
func (mock *QuerierMock) UpsertUserSyncItemCalls() []struct {
	Ctx context.Context
	Arg UpsertUserSyncItemParams
} {
	var calls []struct {
		Ctx context.Context
		Arg UpsertUserSyncItemParams
	}
	mock.lockUpsertUserSyncItem.RLock()
	calls = mock.calls.UpsertUserSyncItem
	mock.lockUpsertUserSyncItem.RUnlock()
	return calls
}
